-- ===========================================================================
-- brainz tenant schema — rung 21, a page the model cannot read
--
-- One column on `page` and one widened CHECK on `consolidation_run`. This rung
-- was drafted twice and the second draft is what shipped, so the argument
-- against the first is part of the rung rather than lost to the branch.
--
-- ---------------------------------------------------------------------------
-- **The failure.**
--
-- A production brain sat at 5,608 pages and 167 facts. Rung 20 named the cause:
-- the cycle stopped in `synopsis`, on a page the model would not summarise. The
-- chain from there is four links long and only the first is about the page — a
-- model phase that stops stops the cycle; a cycle that stops short leaves its
-- run OPEN, because that null `finished_at` is the resume signal; and a model
-- phase holding a checkpoint against an open run is skipped on every resume. So
-- `extract`, banked at its batch bound, was skipped forever. One unusable page
-- stopped extraction for every other page.
--
-- ---------------------------------------------------------------------------
-- **The draft this replaces, and why it was refused.**
--
-- The first draft broke the chain by removing the page: two durable refusals set
-- `page.quarantined_at`, which `selectIngestedPages` already honours, plus a
-- `quarantine_reason` column recording under which code. It worked, and it was
-- the wrong column. `quarantined_at` is U9's junk gate and **every read in the
-- system honours it** — `src/core/search/arms.ts`, the briefing, and the user's
-- own self-export in `src/core/export/reconstruct.ts`. The harm was never "this
-- page is missing from consolidation"; it was a document its owner still has, no
-- longer coming back when they search their own brain, with nothing anywhere
-- saying so.
--
-- And the evidence could not carry that weight. `stopFor` can prove a
-- 400/413/422 is the provider refusing THIS request. It cannot say the same of
-- the widest failure by far — an HTTP 200 whose body will not parse — which is a
-- page the model can never read and a badly sampled answer at once, and which
-- `model-phases.ts` says in as many words it cannot tell apart in one exchange.
-- A provider emitting unparseable 200s under load would have retired real
-- documents on an inference the code admits it cannot make.
--
-- **So nothing is retired.** The phase skips the item it cannot summarise and
-- completes; the page stays a candidate and costs one model call a cycle for as
-- long as it stays unreadable. That is a small, permanent, bounded price, and it
-- is the correct side of the trade against removing somebody's document from
-- their own brain. `quarantine_reason` went with the mechanism it existed for:
-- a reason column for a retirement that cannot happen is a column whose only
-- possible future is somebody finding a use for it.
--
-- ---------------------------------------------------------------------------
-- **`consolidation_refusals` — kept, and now purely telemetry.**
--
-- It survives because the redesign creates the question it answers. Nothing
-- stops any more, so an operator watching a summary count that will not move has
-- to be able to tell three unreadable pages refused forty times each from every
-- page refused once, which is a broken prompt or a seat whose output ceiling is
-- too tight. The per-cycle count in the fleet's `cycle` log says HOW MANY; this
-- says WHICH, and how long it has been going on.
--
-- **Nothing reads it to make a decision, and that is the property to preserve.**
-- The moment a threshold is compared against this column, the refuted draft is
-- back: a counter that decides is a counter whose increments have to be trusted,
-- and the parse-failure increment is exactly the signal that cannot be. It is
-- incremented on the two per-item outcomes the model is answerable for — a
-- durable `input_rejected`, and an answer that could not be parsed — and never
-- by a transient. A provider that is rate-limiting or down stops the phase
-- before any page is charged for it, however long the outage lasts, so an
-- operator reading a non-zero count is never reading an outage.
--
-- `integer` rather than the smallint the first draft used. That draft's counter
-- stopped at a threshold of two; a counter that only counts has no ceiling but
-- the column's, and a page that stays unreadable accumulates one per cycle
-- forever. At smallint's 32,767 the increment inside the phase would eventually
-- raise, which would be a new way for one page to break a run — the exact class
-- of failure this rung exists to remove.
--
-- `NOT NULL DEFAULT 0` rather than nullable: "this page has never been refused"
-- and "nobody has looked" are the same state here, and a nullable counter would
-- invite a reader to distinguish them. The DEFAULT is what keeps the rung
-- expand-only — every INSERT the previous fleet version issues names the old
-- column list and must keep working.
--
-- **The operator's whole view**, deliberately a number and an id rather than a
-- report, and carrying no page content at all:
--
--     SELECT page_id, consolidation_refusals
--       FROM page
--      WHERE consolidation_refusals > 0
--      ORDER BY consolidation_refusals DESC;
--
-- There is no undo statement here, because there is nothing to undo. A page that
-- becomes summarisable — a re-chunk, a bigger seat, a fixed prompt — is
-- summarised on the next cycle with nobody involved, and its count simply stops
-- growing.
--
-- ---------------------------------------------------------------------------
-- **The widened CHECK, and why a drop is admissible here.**
--
-- Rung 20 spelled `PHASE_STOPS` into `consolidation_run_stopped_phase_code_is_known`.
-- `input_rejected` joins that vocabulary and outlives the draft that motivated
-- it, on its own merit: "the provider read the request and refused it" and "the
-- provider never answered" want opposite responses from whoever reads the run
-- record — the first is a request that has to change, the second is a wait — and
-- rung 20's column could say only the second. It now informs diagnosis rather
-- than licensing a retirement, which is the honest use for a signal the phase
-- can trust about the transport and not about the document.
--
-- The DROP is paired with an ADD of the same constraint name in this same rung,
-- which is the one shape `findExpandContractViolations` admits, and the
-- replacement is strictly WIDER: every code the previous fleet version can write
-- is still accepted, so an instance that has never heard of `input_rejected`
-- keeps writing run records through a rolling deploy.
--
-- The narrowing risk a widening rung carries — a code silently dropped from the
-- replacement — is held by `test/consolidate/schema.test.ts`, which asserts
-- against a live database that the alphabet the CHECK accepts is exactly
-- `PHASE_STOPS`, in both directions.
--
-- **Additive, and no backfill.** A page that was refused before this rung has no
-- count to be given and must not be invented one, which is the objection rung 17
-- records against rewriting rows to a cause derived later.
-- ===========================================================================

ALTER TABLE page ADD COLUMN consolidation_refusals integer NOT NULL DEFAULT 0;

ALTER TABLE page ADD CONSTRAINT page_consolidation_refusals_are_counted CHECK (
  consolidation_refusals >= 0
);

-- `PHASE_STOPS`, widened by one. Dropped and re-added under the same name, which
-- is the paired shape the expand-only scanner admits; see the header.
ALTER TABLE consolidation_run DROP CONSTRAINT consolidation_run_stopped_phase_code_is_known;
ALTER TABLE consolidation_run ADD CONSTRAINT consolidation_run_stopped_phase_code_is_known CHECK (
  stopped_phase_code IS NULL
  OR stopped_phase_code IN ('budget_exhausted', 'model_unavailable', 'input_rejected',
                            'bad_output', 'payload_unavailable', 'out_of_time')
);
