/**
 * Skipped stubs for the hazards swept out of gbrain’s guard corpus (U19).
 *
 * GENERATED by `src/upstream/hazard-sweep.ts` — run
 * `bun src/upstream/watch.ts --sweep --write-sweep` to refresh. Edit the decision
 * table in `src/upstream/hazard-map.ts`, never this file.
 *
 * Each stub names a mechanism gbrain guards executably and brainz does not. The
 * reason string is the whole artifact: `bun test` prints it on every run, so the
 * unguarded-hazard count is a number the suite reports rather than a number
 * somebody re-derives. A stub becomes a real test when its card flips to
 * `guarded` in `docs/porting-hazards.md`.
 */

import { test } from 'bun:test';
test.skip("H5 — A real person reaching a public artifact: unported from scripts/check-fixture-privacy.sh, scripts/check-no-pii-in-agent-voice.sh, scripts/check-privacy.sh, scripts/check-proposal-pii.sh, scripts/check-synthetic-corpus-privacy.sh, scripts/check-test-real-names.sh. A scan over committed artifacts for the shapes upstream names — address, phone, bearer, Luhn-valid card, private path prefixes — plus an exact-string blocklist for identifiers a reviewer has flagged. Shape regexes over an allowlist, because a broad corporate-email regex catches legitimate fixture domains and gets switched off.", () => {});

test.skip("H7 — A connection string or a secret leaving through a log line or a serializer: unported from scripts/check-pg-url-redaction.sh, scripts/check-source-config-leak.sh. A source scan, in the shape `test/ai/boundary.test.ts` already uses for the gateway boundary: no module may pass a value derived from the secret store, or a whole config object, to a logging surface or a serializer without a named redaction call in between.", () => {});

test.skip("H8 — A structured value encoded twice on its way into the database: unported from scripts/check-jsonb-params.mjs, scripts/check-jsonb-pattern.sh. A scan asserting that every `::text[]`, `::jsonb` or array-typed bind goes through a named serializer rather than an inline literal, plus a round-trip test per such column that reads the value back through SQL and compares it to what was written — the half a type signature cannot do.", () => {});

test.skip("H9 — A test hook that times out before the work it sets up can finish: unported from scripts/check-bun-test-timeout.sh. A check that every `bun test` invocation in CI configuration and runner scripts passes an explicit `--timeout`, so the budget is a number somebody chose rather than a default nobody saw.", () => {});

test.skip("H10 — Two retry ladders multiplying into one: unported from scripts/check-no-double-retry.sh. A scan asserting no call site wraps a self-retrying primitive in a second retry, plus a test that counts provider invocations across one failing job attempt and pins the number.", () => {});

test.skip("H11 — Non-protocol bytes on the channel a client is parsing: unported from scripts/check-progress-to-stdout.sh. A scan for writes to stdout from any module reachable from the request path, and a server-level test asserting the response body parses as exactly one JSON-RPC message with no leading or trailing bytes.", () => {});

test.skip("H12 — Module-level state leaking between test files in one process: unported from scripts/check-test-isolation.sh. A scan over non-serial test files for module-scope `process.env` mutation and for module-scope state that outlives a file, with an explicit allowlist for the files that genuinely need it.", () => {});

test.skip("H13 — A new union member falling through a switch nobody updated: unported from scripts/check-pagetype-exhaustive.sh. A scan asserting every `switch` over a discriminated union ends in an `assertNever`-shaped default, so the compiler is forced to error when a member is added.", () => {});

test.skip("H14 — A symlink in the repository pointing at one machine: unported from scripts/check-no-tracked-symlinks.sh. A check that `git ls-files -s` reports no entry in mode `120000`.", () => {});

test.skip("H15 — A test that claims determinism and reaches the network anyway: unported from scripts/check-fuzz-purity.sh. Bundle each determinism-claiming entry point and assert the bundle contains no `node:fs`, `node:child_process`, `node:net`, `node:http` or `node:https` — the transitive check the runtime trap cannot make.", () => {});
