/**
 * `docs/register.md`, rendered from {@link SHARED_COMPONENTS}.
 *
 * **Machine-readable and outsider-readable are two requirements, so the document
 * carries two renderings of one source.** A prose table is what an auditor
 * reads; a fenced JSON block is what a script reads. Rendering both from the
 * same array is what stops them disagreeing — and the JSON block is deliberately
 * *in the published document* rather than beside it, because R10 asks that an
 * outsider audit the blast radius **without reading the source**. A machine
 * pointed at `src/register/components.ts` is a machine reading the source.
 *
 * The generated region is spliced between markers, the way
 * `hazard-sweep.ts` splices swept cards, so the hand-written frame around it
 * stays hand-written and a generator never starts owning prose nobody meant it
 * to.
 */

import { NOT_A_DESTINATION, SHARED_COMPONENTS, type RegisterEntry } from './components.ts';

export const REGISTER_DOC_PATH = 'docs/register.md';
export const REGISTER_BEGIN = '<!-- BEGIN register (generated by src/register/render.ts) -->';
export const REGISTER_END = '<!-- END register -->';

/** One table row per component, then the machine block. */
export function renderRegister(
  entries: readonly RegisterEntry[] = SHARED_COMPONENTS,
  excused: readonly { readonly host: string; readonly reason: string }[] = NOT_A_DESTINATION,
): string {
  const lines: string[] = [];

  lines.push('### Components');
  lines.push('');
  lines.push('| id | component | kind | shared by | user content reaches it |');
  lines.push('|---|---|---|---|---|');
  for (const entry of entries) {
    lines.push(
      `| \`${entry.id}\` | ${entry.name} | ${entry.kind} | ${entry.shared_by} | ${entry.transmits_user_content ? '**yes**' : 'no'} |`,
    );
  }
  lines.push('');

  const carrying = entries.filter((entry) => entry.transmits_user_content);
  lines.push(
    `**${carrying.length} of ${entries.length} components receive user content**: ` +
      `${carrying.map((entry) => `\`${entry.id}\``).join(', ')}. Everything else exists for a user ` +
      'without their words reaching it, which is a different question from whether it can hurt them.',
  );
  lines.push('');

  lines.push('### Blast radius and rotation');
  lines.push('');
  for (const entry of entries) {
    lines.push(`#### \`${entry.id}\` — ${entry.name}`);
    lines.push('');
    lines.push(
      `**Kind.** ${entry.kind} · **Shared by.** ${entry.shared_by} · ` +
        `**Receives user content.** ${entry.transmits_user_content ? 'yes' : 'no'}`,
    );
    lines.push('');
    lines.push(`**Blast radius.** ${entry.blast_radius}`);
    lines.push('');
    lines.push(`**Rotation owner.** ${entry.rotation_owner}`);
    lines.push('');
    lines.push(`**Rotation.** ${entry.rotation}`);
    if (entry.note !== undefined) {
      lines.push('');
      lines.push(`**Note.** ${entry.note}`);
    }
    lines.push('');
    lines.push(`**Evidence in the code.** ${evidenceOf(entry)}`);
    lines.push('');
  }

  lines.push('### Hosts named in source that are not destinations');
  lines.push('');
  lines.push(
    'The host sweep is a literal match, so a URL in a comment counts. Over-reporting is the ' +
      'right direction of error for a blast-radius list; each over-report is answered here, once, ' +
      'in writing.',
  );
  lines.push('');
  for (const entry of excused) {
    lines.push(`- \`${entry.host}\` — ${entry.reason}`);
  }
  lines.push('');

  lines.push('### The same register, for a machine');
  lines.push('');
  lines.push(
    'Identical content, so a script auditing the blast radius reads the published document ' +
      'rather than the source it was generated from.',
  );
  lines.push('');
  lines.push('```json');
  lines.push(JSON.stringify({ components: entries, not_a_destination: excused }, null, 2));
  lines.push('```');

  return lines.join('\n');
}

function evidenceOf(entry: RegisterEntry): string {
  const parts: string[] = [];
  const { hosts, providers, bindings } = entry.evidence;
  if (hosts !== undefined && hosts.length > 0) {
    parts.push(`hosts ${hosts.map((host) => `\`${host}\``).join(', ')}`);
  }
  if (providers !== undefined && providers.length > 0) {
    parts.push(`routing providers ${providers.map((id) => `\`${id}\``).join(', ')}`);
  }
  if (bindings !== undefined && bindings.length > 0) {
    parts.push(`deployment bindings ${bindings.map((id) => `\`${id}\``).join(', ')}`);
  }
  if (parts.length === 0) {
    // Said rather than left blank: an entry with no scanner evidence is one a
    // human put there, and a reader should know which kind they are looking at.
    return 'none a scanner can find — this component is named because it exists, not because a sweep reported it.';
  }
  return `${parts.join('; ')}.`;
}

/** Splice the generated region into the hand-written document. */
export function spliceRegister(document: string, rendered: string): string {
  const begin = document.indexOf(REGISTER_BEGIN);
  const end = document.indexOf(REGISTER_END);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error(
      `${REGISTER_DOC_PATH} is missing the generated-region markers (${REGISTER_BEGIN} … ${REGISTER_END}). ` +
        'Refusing to write: a generator that appends to a hand-written document will eventually own it.',
    );
  }
  return `${document.slice(0, begin + REGISTER_BEGIN.length)}\n\n${rendered}\n\n${document.slice(end)}`;
}
